---
- name: Install Docker and Deploy Nginx
  hosts: private_servers
  become: true
  vars:
    ansible_ssh_private_key_file: /home/ubuntu/tera.pem
  roles:
    - docker_install

  tasks:
    - name: Pull the latest Nginx image
      docker_image:
        name: nginx
        source: pull

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"
